version: '3.1'

services:
  node:
    build: .
    ports:
      - 5000:5000

  db:
    container_name: postgres
    image: postgres:15
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: